
import 'package:e2_info/controller/pokemon_details_controller/pokemon_details_controller.dart';
import 'package:e2_info/controller/pokemons_list_controller/pokemons_list_controller.dart';

PokemonListController pokemonListController = PokemonListController.instance;
PokemonDetailsController pokemonDetailsController = PokemonDetailsController.instance;